server:
  tomcat:
    threads:
      min-spare: 8
      max: 8
spring:
  data:
    redis:
      host: '[::1]'
  datasource:
    url: jdbc:postgresql://10.0.0.154/iris
    username: dbuser
    password: dbuser
    hikari:
      maximum-pool-size: 10
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false